import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = True
VISUALIZED_PERIODS = 10

LABEL_TO_INDEX_DICT = {
    "excited": 0,
    "focused": 1,
    "relaxed": 2
}

INDEX_TO_LABEL_DICT = {
    0: "excited",
    1: "focused",
    2: "relaxed"
}

TIMER_CSV_PATH = os.path.abspath(os.getenv('TIMER_CSV_PATH'))
TEST_RESULTS = os.path.abspath(os.getenv('TEST_RESULTS'))

NN_PARAMS_SCHEMA = os.getenv("NN_PARAMS_SCHEMA")
NN_PARAMS_CONFIG_DIR = os.getenv("NN_PARAMS_CONFIG_DIR")
NN_RESULTS_DIR = os.getenv("NN_RESULTS_DIR")
NN_MODELS_DIR = os.getenv("NN_MODELS_DIR")
NN_LEARNING_SETS_DIR = os.getenv("NN_LEARNING_SETS_DIR")
NN_OPERATIVE_SETS_DIR = os.getenv("NN_OPERATIVE_SETS_DIR")

DATA_PREP_CONFIG_PATH = os.path.abspath(os.getenv("DATA_PREP_CONFIG_FILE"))
DATA_PREP_POLLING_CONFIG = os.path.abspath(os.getenv("DATA_PREP_POLLING_CONFIG"))
DATA_PREP_INPUT_PATH = os.path.abspath(os.getenv("DATA_PREP_INPUT_PATH"))
DATA_PREP_INPUT_SCHEMA = os.path.abspath(os.getenv('DATA_PREP_INPUT_SCHEMA'))
DATA_PREP_INPUT_BASENAME = 'TrainingSessions'
DATA_PREP_OPERATIVE_OUTPUT_PATH = os.path.abspath(os.getenv("DATA_PREP_OPERATIVE_OUTPUT_PATH"))
DATA_PREP_TRAINING_OUTPUT_PATH = os.path.abspath(os.getenv("DATA_PREP_TRAINING_OUTPUT_PATH"))
DATA_PREP_PROCESSED_TIMESTAMPS = os.path.abspath(os.getenv("DATA_PREP_PROCESSED_TIMESTAMPS"))
DATA_PREP_LOG_FILE = os.path.abspath(os.getenv('DATA_PREP_LOG_FILE'))

PERF_MONITORING_CONF_DIR = os.getenv("PERF_MONITORING_CONF_DIR")
PERF_MONITORING_SCHEMA = os.getenv("PERF_MONITORING_SCHEMA")
PERF_MONITORING_HISTORICAL = os.getenv("PERF_MONITORING_HISTRORICAL")
PERF_MONITORING_RESULTS = os.getenv("PERF_MONITORING_RESULTS")
PERF_MONITORING_LOGFILE = os.getenv("PERF_MONITORING_LOGFILE")

RACC_CONFIG_FILE = os.getenv("RACC_CONFIG_FILE")
RACC_CONFIG_SCEMA = os.getenv("RACC_CONFIG_SCEMA")
RACC_DATASET_INPUT = os.getenv("RACC_DATASET_INPUT")
RACC_OUTPUT_BASE_PATH = os.getenv("RACC_OUTPUT_BASE_PATH")
RACC_LOG_FILE = os.getenv("RACC_LOG_FILE")

SESSIONI_RACCOLTE_SCHEMA = os.getenv("SESSIONI_RACCOLTE_SCHEMA")
SESSIONE_DA_CLASSIFICARE_SCHEMA = os.getenv("SESSIONE_DA_CLASSIFICARE_SCHEMA")

REPORTS_DIRECTORY_PATH = os.getenv("REPORTS_DIRECTORY_PATH")

GEN_INSIEMI_LEARNING_CONFIG_PATH_QC = os.getenv("GEN_INSIEMI_LEARNING_CONFIG_PATH_QC")
GEN_INSIEMI_LEARNING_CONFIG_PATH_GEN = os.getenv("GEN_INSIEMI_LEARNING_CONFIG_PATH_GEN")
GEN_INSIEMI_LEARNING_CONFIG_PATH_MOD = os.getenv("GEN_INSIEMI_LEARNING_CONFIG_PATH_MOD")
GEN_INSIEMI_LEARNING_SCHEMA_PATH_GEN = os.getenv("GEN_INSIEMI_LEARNING_SCHEMA_PATH_GEN")
GEN_INSIEMI_LEARNING_SCHEMA_PATH_QC = os.getenv("GEN_INSIEMI_LEARNING_SCHEMA_PATH_QC")
GEN_INSIEMI_LEARNING_SCHEMA_PATH_MOD = os.getenv("GEN_INSIEMI_LEARNING_SCHEMA_PATH_MOD")
GEN_INSIEMI_LEARNING_SCHEMA_PATH_INPUT = os.getenv("GEN_INSIEMI_LEARNING_SCHEMA_PATH_INPUT")

